---
apiVersion: v1
kind: ReplicationController
metadata:
 name: httpd-rc
 labels:
  author: chiru
spec:
 replicas: 4
 template:
  metadata:
   name: httpd-pod
   labels:
    name: chiru
  spec:
   containers:
    - name: httpd-con
      image: httpd
      ports:
       - containerPort: 80
         hostPort: 8080
         
...

